services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
     - 5433:5432
    env_file:
      - .env

  node:
    container_name: node
    build: .
    image: fullstack/backend
    ports:
     - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
