name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_SECRET: "teste"
          envkey_PORT: 5000
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "autoral"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/autoral"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test